#!/usr/bin/env python3

import sys
from subprocess import Popen, PIPE
from math import prod

def main(file_path):
    with open(file_path, 'r') as file:
        for line in file:
            number = int(line.strip())
            factors = factor(number)
            formatted_output = format_output(number, factors)
            print(formatted_output)

def factor(n):
    process = Popen(['factor', str(n)], stdout=PIPE)
    (output, _) = process.communicate()
    return output.decode('utf-8').strip()

def format_output(number, factor_string):
    _, factors_str = factor_string.split(': ')
    factors = [int(f) for f in factors_str.split(' ')]
    
    if len(factors) > 2:
        non_trivial_divisor = prod(factors[1:])
    else:
        non_trivial_divisor = factors[1]
    
    if factors[0] > non_trivial_divisor:
        return f"{number}={factors[0]}*{non_trivial_divisor}"
    else:
        return f"{number}={non_trivial_divisor}*{factors[0]}"

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print('Usage: ./factors <file>')
        sys.exit(1)
    main(sys.argv[1])
