#!/usr/bin/env python3

import sys
from subprocess import Popen, PIPE

def main(file_path):
    with open(file_path, 'r') as file:
        for line in file:
            number = int(line.strip())
            factors = factorize_all_pairs(number)
            for factor1, factor2 in factors:
                print(f"{number}={factor1}*{factor2}")

def factorize_all_pairs(n):
    process = Popen(['factor', str(n)], stdout=PIPE)
    (output, _) = process.communicate()
    output = output.decode('utf-8').strip()
    
    _, factors_str = output.split(': ')
    factors = [int(factor) for factor in factors_str.split(' ')]
    pairs = []
    for i in range(len(factors)):
        for j in range(i+1, len(factors)):
            pairs.append((factors[i], factors[j]))
    return pairs

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print('Usage: ./factors <file>')
        sys.exit(1)
    main(sys.argv[1])
