#!/usr/bin/env python3

import sys
from subprocess import Popen, PIPE

def main(file_path):
    with open(file_path, 'r') as file:
        for line in file:
            number = int(line.strip())
            factor1, factor2 = factorize_first_pair(number)
            if factor1 < factor2:
                factor1, factor2 = factor2, factor1
            print(f"{number}={factor1}*{factor2}")

def factorize_first_pair(n):
    process = Popen(['factor', str(n)], stdout=PIPE)
    (output, _) = process.communicate()
    output = output.decode('utf-8').strip()
    
    _, factors_str = output.split(': ')
    factors = factors_str.split(' ')
    first_factor = int(factors[0])
    second_factor = n // first_factor
    return (second_factor, first_factor) if second_factor > first_factor else (first_factor, second_factor)

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print('Usage: ./factors <file>')
        sys.exit(1)
    main(sys.argv[1])
